// Bordering US states + Canadian provinces, including cross-border pairs.
// Used by leg grouping so two shows only chain into one pamphlet when their
// regions actually touch — a 6-day gap between WA and NJ is not a tour leg.
const ADJACENCY: Record<string, string[]> = {
  // US states
  AL: ["FL", "GA", "MS", "TN"],
  AZ: ["CA", "CO", "NM", "NV", "UT"],
  AR: ["LA", "MO", "MS", "OK", "TN", "TX"],
  CA: ["AZ", "NV", "OR"],
  CO: ["AZ", "KS", "NE", "NM", "OK", "UT", "WY"],
  CT: ["MA", "NY", "RI"],
  DE: ["MD", "NJ", "PA"],
  DC: ["MD", "VA"],
  FL: ["AL", "GA"],
  GA: ["AL", "FL", "NC", "SC", "TN"],
  ID: ["MT", "NV", "OR", "UT", "WA", "WY", "BC"],
  IL: ["IN", "IA", "KY", "MO", "WI"],
  IN: ["IL", "KY", "MI", "OH"],
  IA: ["IL", "MN", "MO", "NE", "SD", "WI"],
  KS: ["CO", "MO", "NE", "OK"],
  KY: ["IL", "IN", "MO", "OH", "TN", "VA", "WV"],
  LA: ["AR", "MS", "TX"],
  ME: ["NH", "QC", "NB"],
  MD: ["DC", "DE", "PA", "VA", "WV"],
  MA: ["CT", "NH", "NY", "RI", "VT"],
  MI: ["IN", "OH", "WI", "ON"],
  MN: ["IA", "ND", "SD", "WI", "MB", "ON"],
  MS: ["AL", "AR", "LA", "TN"],
  MO: ["AR", "IA", "IL", "KS", "KY", "NE", "OK", "TN"],
  MT: ["ID", "ND", "SD", "WY", "BC", "AB", "SK"],
  NE: ["CO", "IA", "KS", "MO", "SD", "WY"],
  NV: ["AZ", "CA", "ID", "OR", "UT"],
  NH: ["ME", "MA", "VT", "QC"],
  NJ: ["DE", "NY", "PA"],
  NM: ["AZ", "CO", "OK", "TX", "UT"],
  NY: ["CT", "MA", "NJ", "PA", "VT", "ON", "QC"],
  NC: ["GA", "SC", "TN", "VA"],
  ND: ["MN", "MT", "SD", "SK", "MB"],
  OH: ["IN", "KY", "MI", "PA", "WV", "ON"],
  OK: ["AR", "CO", "KS", "MO", "NM", "TX"],
  OR: ["CA", "ID", "NV", "WA"],
  PA: ["DE", "MD", "NJ", "NY", "OH", "WV", "ON"],
  RI: ["CT", "MA"],
  SC: ["GA", "NC"],
  SD: ["IA", "MN", "MT", "ND", "NE", "WY"],
  TN: ["AL", "AR", "GA", "KY", "MO", "MS", "NC", "VA"],
  TX: ["AR", "LA", "NM", "OK"],
  UT: ["AZ", "CO", "ID", "NM", "NV", "WY"],
  VT: ["MA", "NH", "NY", "QC"],
  VA: ["DC", "KY", "MD", "NC", "TN", "WV"],
  WA: ["ID", "OR", "BC"],
  WV: ["KY", "MD", "OH", "PA", "VA"],
  WI: ["IA", "IL", "MI", "MN"],
  WY: ["CO", "ID", "MT", "NE", "SD", "UT"],
  // Canadian provinces / territories
  BC: ["AB", "YT", "NT", "WA", "ID", "MT", "AK"],
  AB: ["BC", "SK", "NT", "MT"],
  SK: ["AB", "MB", "NT", "MT", "ND"],
  MB: ["SK", "ON", "NU", "NT", "ND", "MN"],
  ON: ["MB", "QC", "MN", "MI", "OH", "PA", "NY"],
  QC: ["ON", "NB", "NL", "NY", "VT", "NH", "ME"],
  NB: ["QC", "NS", "PE", "ME"],
  NS: ["NB", "PE"],
  PE: ["NB", "NS"],
  NL: ["QC"],
  YT: ["BC", "NT", "AK"],
  NT: ["YT", "NU", "BC", "AB", "SK", "MB"],
  NU: ["NT", "MB"],
  AK: ["BC", "YT"],
};

// True when two region codes border each other (order-independent).
export function areRegionsAdjacent(a: string, b: string): boolean {
  if (!a || !b || a === b) return a === b;
  return !!ADJACENCY[a]?.includes(b) || !!ADJACENCY[b]?.includes(a);
}
